# Generated by Django 4.1 on 2022-08-10 23:49

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ataque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                (
                    "clase",
                    models.CharField(
                        choices=[("Fisico", "Fisico"), ("Especial", "Especial")],
                        max_length=8,
                    ),
                ),
                ("descripcion", models.CharField(max_length=9999)),
            ],
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "slug",
                    models.SlugField(
                        max_length=255, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("titulo", models.CharField(max_length=255, unique=True)),
                ("subtitulo", models.CharField(blank=True, max_length=255)),
                ("cuerpo", ckeditor.fields.RichTextField()),
                ("descripcion", models.CharField(blank=True, max_length=150)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                ("fecha_publicacion", models.DateTimeField(blank=True, null=True)),
                ("publicado", models.BooleanField(default=False)),
                ("imagen", models.ImageField(upload_to="")),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, to="posts.tag")),
            ],
            options={
                "ordering": ["-fecha_publicacion"],
            },
        ),
        migrations.CreateModel(
            name="Pokemon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                (
                    "ataque_1",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ataque_1",
                        to="posts.ataque",
                    ),
                ),
                (
                    "ataque_2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ataque_2",
                        to="posts.ataque",
                    ),
                ),
                (
                    "ataque_3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ataque_3",
                        to="posts.ataque",
                    ),
                ),
                (
                    "ataque_4",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ataque_4",
                        to="posts.ataque",
                    ),
                ),
                (
                    "tipo_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tipo_1",
                        to="posts.tipo",
                    ),
                ),
                (
                    "tipo_2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tipo_2",
                        to="posts.tipo",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ataque",
            name="tipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="posts.tipo"
            ),
        ),
    ]
