# Generated by Django 4.0.5 on 2022-07-15 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ataque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('clase', models.CharField(choices=[('Fisico', 'Fisico'), ('Especial', 'Especial')], max_length=8)),
                ('tipo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=9999)),
            ],
        ),
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('genero', models.CharField(choices=[('H', 'H'), ('M', 'M'), ('NB', 'NB')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo_1', models.CharField(max_length=50)),
                ('tipo_2', models.CharField(max_length=50)),
                ('ataque_1', models.CharField(max_length=50)),
                ('ataque_2', models.CharField(max_length=50)),
                ('ataque_3', models.CharField(max_length=50)),
                ('ataque_4', models.CharField(max_length=50)),
                ('id_pokedex', models.IntegerField()),
                ('genero', models.CharField(choices=[('H', 'H'), ('M', 'M')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_1', models.CharField(max_length=30)),
                ('tipo_2', models.CharField(max_length=30)),
            ],
        ),
    ]
