# Generated by Django 4.0.5 on 2022-07-21 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_delete_entrenador_alter_pokemon_ataque_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipo',
            old_name='tipo_1',
            new_name='tipo',
        ),
        migrations.RemoveField(
            model_name='tipo',
            name='tipo_2',
        ),
        migrations.AlterField(
            model_name='ataque',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App1.tipo'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='tipo_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipo_1', to='App1.tipo'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='tipo_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipo_2', to='App1.tipo'),
        ),
    ]
