# Generated by Django 4.0.5 on 2022-07-21 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_rename_tipo_1_tipo_tipo_remove_tipo_tipo_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='tipo_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tipo_2', to='App1.tipo'),
        ),
    ]
