# Generated by Django 4.0.5 on 2022-07-21 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0005_alter_pokemon_ataque_2_alter_pokemon_ataque_3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='id_pokedex',
        ),
    ]
